##学習データ取得用 PG

In [12]:
 #Colaboratoryへファイルをアップロード
 from google.colab import files
 uploaded = files.upload()

Saving 17jepj6UYBY31xy7oic9eC4meKwtX4dHS to 17jepj6UYBY31xy7oic9eC4meKwtX4dHS


In [2]:
!pip install bs4

In [13]:
import requests as web
import bs4
import csv
import time
import re

# 検索数
limit_cnt_per_key = 3
regPtn = '[亜-熙ぁ-んァ-ヶ]{10,}'  # 日本語のみ取得

# これがないと説明文とれない
user_agent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6)" \
     "AppleWebKit/537.36 (KHTML, like Gecko)" \
     "Chrome/88.0.4324.109"

#user_agent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.81 Safari/537.36"
#user_agent = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36"

with open('keys.csv', encoding='utf8') as keyListFile:
    with open('g_output.csv','w',newline='',encoding='utf8') as outcsv:
        csvwriter = csv.writer(outcsv)
        csvwriter.writerow(['No','判定','曲名','説明'])
        cntMusic = 0
        key_list = csv.reader(keyListFile)
        for key in key_list:
            resp = web.get('https://www.google.co.jp/search?num=100&q=' + '　'.join(key[0] + '　歌詞　意味')
                    , headers={"User-Agent": user_agent})
            resp.raise_for_status()

            time.sleep(5) # スリープ
            # time.sleep(0.5)

            # 取得したHTMLをパースする
            resp.encoding = 'utf8'  # 文字コード
            soup = bs4.BeautifulSoup(resp.text, "html.parser")
            #soup.find("span", {"class":"f"}).extract()

            print(soup.title)

            # 検索結果の説明部分を取得
            contentList = soup.select('div > .tF2Cxc > .IsZvec span') # classの部分はdev toolsで確認する
            cnt_per_key = 0;
            for content in contentList:
                # 説明のテキスト部分のみを取得/余分な改行コードは削除する
                content_text = content.get_text().replace('\n','').replace('\r','')
                if(re.search(regPtn, content_text)):
                    print([cntMusic,'T', key[0], content_text])
                    csvwriter.writerow([cntMusic,'T', key[0], content_text])
                    cntMusic += 1
                    cnt_per_key +=1
                if cnt_per_key >= limit_cnt_per_key: break 

<title>蕾　（　コ　ブ　ク　ロ　）　　　歌　詞　　　意　味 - Google Search</title>
[0, 'T', '蕾（コブクロ）', '「蕾」の歌詞の意味を読み解く. 『蕾』は亡き母に捧げられた歌.']
[1, 'T', '蕾（コブクロ）', '今回は亡き母へと綴られた「蕾」の歌詞に迫ってみようと思います。 kyohei. コブクロの代表曲！ ドラマ主題歌としても人気の曲.']
[2, 'T', '蕾（コブクロ）', 'どうも こんにちは。 16才男のコブクロファンです。 質問者様がご指摘の部分は》僕ら この街に落とされた影法師みんな 光を探して重なり合う時の流れもきっと きっと\xa0...']
<title>真　夏　の　果　実　　　歌　詞　　　意　味 - Google Search</title>
[3, 'T', '真夏の果実', '真夏の果実」は、桑田佳祐の監督作品映画『稲村ジェーン』主題歌など、CMソングやドラマの挿入歌としても使用されました。桑田佳祐が作詞した歌詞とPV\xa0...']
[4, 'T', '真夏の果実', 'フジファブリックさんの夏の終わりの名曲「若者のすべて」でも同じく歌詞に「君」という言葉が出てこないことで君という存在が不在であることをより強調\xa0...']
[5, 'T', '真夏の果実', 'サザンオールスターズの名曲「真夏の果実」の歌詞の意味について。 私はサザンの真夏の果実が大好きです。しかし歌詞を見ながらじっくり聞くと理解できないフレーズ\xa0...']
<title>木　綿　の　ハ　ン　カ　チ　ー　フ　　　歌　詞　　　意　味 - Google Search</title>
[6, 'T', '木綿のハンカチーフ', 'また、松本隆はこの曲のタイトルに敢えて「コットン」ではなく「木綿」という当時でもあまり使われなくなった言葉を使いました。 「ハンカチ」を「\xa0...']
[7, 'T', '木綿のハンカチーフ', '4コーラス目、「最後のわがまま贈り物をねだるわ」っていうんですが、これ、ふつうの人は「この女子のはじめてのおねだりが木綿のハンカチなのだな、なんて質素でいい子\xa0...']
[8, 'T', '木綿のハンカチーフ', '太田最大のヒット曲にして代表曲であり、翌1976年末の『第

In [16]:
import requests as web
import bs4
import csv
import time

# 検索数
limit_cnt_per_key = 20
regPtn = '[亜-熙ぁ-んァ-ヶ]{10,}'  # 日本語のみ取得

# これがないと説明文とれない
user_agent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6)" \
     "AppleWebKit/537.36 (KHTML, like Gecko)" \
     "Chrome/88.0.4324.109"

with open('g_output.csv','w',newline='',encoding='utf8') as outcsv:
    csvwriter = csv.writer(outcsv)
    csvwriter.writerow(['No','判定','曲名','説明'])
    cntMusic = 0
    # key_list = csv.reader(keyListFile)
    key_list = [["健康 食べ物"],  ["吉祥寺 ライブ酒場"], ["吉祥寺 ライブ酒場 南郷7丁目 評判"]]

    for key in key_list:
        resp = web.get('https://www.google.co.jp/search?num=100&q=' + '　'.join(key[0] + '')
                , headers={"User-Agent": user_agent})
        resp.raise_for_status()

        time.sleep(5) # スリープ

        # 取得したHTMLをパースする
        resp.encoding = 'utf8'  # 文字コード
        soup = bs4.BeautifulSoup(resp.text, "html.parser")

        # 検索結果の説明部分を取得
        contentList = soup.select('div > .tF2Cxc > .IsZvec span') # classの部分はdev toolsで確認する
        cnt_per_key = 0;
        for content in contentList:
            # 説明のテキスト部分のみを取得/余分な改行コードは削除する
            content_text = content.get_text().replace('\n','').replace('\r','')
            if(re.search(regPtn, content_text)):
                print([cntMusic,'T', key[0], content_text])
                csvwriter.writerow([cntMusic,'T', key[0], content_text])
                cntMusic += 1
                cnt_per_key +=1
            if cnt_per_key >= limit_cnt_per_key: break 

[0, 'T', '健康 食べ物', '健康になるためにと果汁100％のジュースを飲んでいる人がいる。また、βカロテンやリコピンといった成分を気にしている人も多い。']
[1, 'T', '健康 食べ物', '食と健康のプロフェッショナルである管理栄養士。彼らが日頃から意識して食べているものは何なのでしょうか…？今回は33名の管理栄養士へのアンケート\xa0...']
[2, 'T', '健康 食べ物', '発酵食品であり、食物繊維摂取にもなり、腸内環境の整える働きもあるため。 栄養価が豊富。ダイエットや美肌にも効果的。安いし・食べるものが無いという\xa0...']
[3, 'T', '健康 食べ物', 'できることなら体に良くておいしい物を食べて健康になりたいと思いませんか？ 今回は「体に良いとされている食べ物6選」や「おいしい簡単レシピ」「余裕が\xa0...']
[4, 'T', '健康 食べ物', '健康的な食生活を目指している人に対し、どの栄養士も「まずは自分の体に合った食事量を知ることが大事」とアドバイスするだろう。']
[5, 'T', '健康 食べ物', 'サラダに混ぜたり、野菜とも相性の良いおかずになります。赤肉をあまり食べないようにし、ベーコンやソーセージなどの加工肉の摂取を控えましょう。 健康的な植物\xa0...']
[6, 'T', '健康 食べ物', '楽天市場-「食べ物と健康 食品の機能」25件 人気の商品を価格比較・ランキング･レビュー・口コミで検討できます。ご購入でポイント取得がお得。']
[7, 'T', '健康 食べ物', 'Amazonで直道, 國崎, 正孝, 西塔の食べ物と健康―食品の栄養成分と加工。アマゾンならポイント還元本が多数。直道, 國崎, 正孝, 西塔作品ほか、お急ぎ便対象商品は当日\xa0...']
[8, 'T', '健康 食べ物', 'Amazonで高岡 素子, 高岡 素子の新版 食べ物と健康[食品学総論](第2版)。アマゾンならポイント還元本が多数。高岡 素子, 高岡 素子作品ほか、お急ぎ便対象商品は当日お\xa0...']
[9, 'T', '健康 食べ物', 'ちなみに、日本人の一日の平均摂取量は男性で11.0g、女性で9.2gですから（平成27年国民健康・栄養調査）、この目標はなかなか厳しい数値です

In [ ]:
# 数学的確率
    """ 理論的に出した確率
    一枚のコインを投げた時、出る結果には表裏の2通りがあり、
    表が出るのは、そのうちの一通りだから、
    表が出る確率は1/2という考え方。
    """

# 統計的確率
    """ 実際の結果から出した確率
    一枚のコインを実際に繰り返し投げ、
    表の出た結果の割合から出した確率のこと。
    """

# 場合の数
    """ ある出来事の結果どのような場合があるか
    重複なく数え上げた合計数
    """

# 確率
    """確率を求めたいことが起きる場合の数/そのことが起きる全ての場合の数"""

# 和の法則

# 積の法則

# 順列（異なるn個のものからr個を選んだ並べ方 nPr）

# 階乗（n個からn個とって並べた順列）

# 組合わせ（nCr）
""" 異なるn個のものからr個を選ぶ時の組合せ
    順序を考えないで選ぶことを「組合せ」
    nCr=npr/r!
"""

In [ ]:
import math

def get_permutation(n, r):
    """ 順列の総数を返す関数
    異なるn個のものからr個を選んだ並べ方
    """
    return math.factorial(n) // math.factorial(n - r)


def get_combination(n, r):
    """ 組合せの総数を返す関数
    順序を考えないで選ぶことを「組合せ」
    nCr=npr/r!
    """
    return get_permutation(n, r) // math.factorial(r)



def main():
    print("順列: " + str(get_permutation(10, 3)))
    print("組合せ: " + str(get_combination(4, 2)))


if __name__ == "__main__":
    main()

順列: 720
組合せ: 6


In [ ]:
import random
import itertools

# 食事
def do_meal(price, time_hour):
    happiness = 100 * price * time_hour
    return happiness

# 制約
def remain_hp(used_money, used_time):
    remain_money = 28 - used_money
    remain_time = 24 * 30 - used_time
    return [remain_money, remain_time]

# 快速電車　確率
def bk_get_good_train():
    # print(random.uniform(100, 200))

    element_list = ['特快', '快速', '各停']
    prob_list = [0.1, 0.3, 0.6]
    sample_size = 100

    samples = random.choices(element_list, k = sample_size, weights = prob_list)

    # 結果の確認
    for i in element_list:
        print(i, ':', samples.count(i))


def get_good_train():
    element_list = ['特快', '快速', '各停']
    prob_list = [0.1, 0.3, 0.6]
    sample_size = 1

    samples = random.choices(element_list, k = sample_size, weights = prob_list)
    print(samples)

    if "快速" == samples[0]:
        return 10
    else:
        return 2

def get_perm():
    elem_list = ["食事", "テレビ", "お風呂", "洗濯", "睡眠"]
    comb = itertools.combinations(elem_list, 3)
    return list(comb)

def main():
    print("食事: " + str(do_meal(0.06, 1)))
    print("制約: " + str(remain_hp(0.06, 1)))
    print("電車確率: " + str(get_good_train()))
    print(get_perm())

    list_mo = []
    for str_m in get_perm():
        for moji in str_m:
            list_mo.append(moji)

    print(list(map(lambda str_moji : str_moji + "test", list_mo)))

if __name__ == "__main__":
    main()

食事: 6.0
制約: [27.94, 719]
['快速']
電車確率: 10
[('食事', 'テレビ', 'お風呂'), ('食事', 'テレビ', '洗濯'), ('食事', 'テレビ', '睡眠'), ('食事', 'お風呂', '洗濯'), ('食事', 'お風呂', '睡眠'), ('食事', '洗濯', '睡眠'), ('テレビ', 'お風呂', '洗濯'), ('テレビ', 'お風呂', '睡眠'), ('テレビ', '洗濯', '睡眠'), ('お風呂', '洗濯', '睡眠')]
['食事test', 'テレビtest', 'お風呂test', '食事test', 'テレビtest', '洗濯test', '食事test', 'テレビtest', '睡眠test', '食事test', 'お風呂test', '洗濯test', '食事test', 'お風呂test', '睡眠test', '食事test', '洗濯test', '睡眠test', 'テレビtest', 'お風呂test', '洗濯test', 'テレビtest', 'お風呂test', '睡眠test', 'テレビtest', '洗濯test', '睡眠test', 'お風呂test', '洗濯test', '睡眠test']


In [ ]:
import itertools


act_list = ['お風呂', '睡眠', '食事', 'テレビ', 'ギター', 'ウクレレ']
happiness_list = [30, 20, 50, 15, 40, 30]
money_list = [100, 0, 700, 100, 10, 10]
time_list = [0.5, 4, 0.5, 3, 1, 0.5]

decision_dic = dict(zip(act_list, zip(happiness_list, money_list, time_list)))

print(decision_dic)

cnt = 0
max_fx = -100000
max_combi = ""
max_happiness = 0
max_money = 0
max_time = 0
for sel_num in range(len(act_list)):
    comb_list = list(itertools.combinations(act_list, sel_num + 1))
    for acts in comb_list:
        cnt +=1
        happiness_sum = 0
        money_sum = 0
        time_sum = 0
        fx = 0
        for act in acts:
            happiness_sum += decision_dic[act][0]
            money_sum += decision_dic[act][1]
            time_sum += decision_dic[act][2]
        # fx = 1 * happiness_sum - abs(250-money_sum) - abs(6-time_sum)
        fx = 1.5 * happiness_sum/sum(happiness_list) - money_sum/sum(money_list) \
             - time_sum/sum(time_list)
        if fx > max_fx:
            max_fx = fx
            max_combi = acts
            max_happiness = happiness_sum
            max_money = money_sum
            max_time = time_sum

print(cnt)
print(max_fx)
print(max_combi)
print(max_happiness)
print(max_money)
print(max_time)


{'お風呂': (30, 100, 0.5), '睡眠': (20, 0, 4), '食事': (50, 700, 0.5), 'テレビ': (15, 100, 3), 'ギター': (40, 10, 1), 'ウクレレ': (30, 10, 0.5)}
63
0.4698497124126415
('お風呂', 'ギター', 'ウクレレ')
100
120
2.0


In [17]:
import pandas as pd
import itertools

act_list = ['お風呂', '睡眠', '食事', 'テレビ', 'ギター', 'ウクレレ']
happiness_list = [30, 20, 50, 15, 40, 30]
money_list = [100, 0, 700, 100, 10, 10]
time_list = [0.5, 4, 0.5, 3, 1, 0.5]

decision_dic = dict(zip(act_list, zip(happiness_list, money_list, time_list)))

print(decision_dic)

comb_list = list(itertools.combinations(act_list, 3))
# pd.Series(comb_list).map(lambda x: print(str(x) + " : test"))
pd.Series(comb_list).apply(lambda x: print(str(x) + " : test"))

{'お風呂': (30, 100, 0.5), '睡眠': (20, 0, 4), '食事': (50, 700, 0.5), 'テレビ': (15, 100, 3), 'ギター': (40, 10, 1), 'ウクレレ': (30, 10, 0.5)}
('お風呂', '睡眠', '食事') : test
('お風呂', '睡眠', 'テレビ') : test
('お風呂', '睡眠', 'ギター') : test
('お風呂', '睡眠', 'ウクレレ') : test
('お風呂', '食事', 'テレビ') : test
('お風呂', '食事', 'ギター') : test
('お風呂', '食事', 'ウクレレ') : test
('お風呂', 'テレビ', 'ギター') : test
('お風呂', 'テレビ', 'ウクレレ') : test
('お風呂', 'ギター', 'ウクレレ') : test
('睡眠', '食事', 'テレビ') : test
('睡眠', '食事', 'ギター') : test
('睡眠', '食事', 'ウクレレ') : test
('睡眠', 'テレビ', 'ギター') : test
('睡眠', 'テレビ', 'ウクレレ') : test
('睡眠', 'ギター', 'ウクレレ') : test
('食事', 'テレビ', 'ギター') : test
('食事', 'テレビ', 'ウクレレ') : test
('食事', 'ギター', 'ウクレレ') : test
('テレビ', 'ギター', 'ウクレレ') : test


0     None
1     None
2     None
3     None
4     None
5     None
6     None
7     None
8     None
9     None
10    None
11    None
12    None
13    None
14    None
15    None
16    None
17    None
18    None
19    None
dtype: object

In [18]:
import math

comb3=list(itertools.combinations(act_list, 3))
print(list(map(lambda acts: sum(decision_dic[act][0] for act in acts) , comb3)))

print(list(map(lambda acts: sum(list(map(lambda act: decision_dic[act][0], acts))) , comb3)))


print(list(map(lambda acts: sum(list(map(lambda act: decision_dic[act][0] - abs(decision_dic[act][1]) - abs(decision_dic[act][2]), acts))) , comb3)))

[100, 65, 90, 80, 95, 120, 110, 85, 75, 100, 85, 110, 100, 75, 65, 90, 105, 95, 120, 85]
[100, 65, 90, 80, 95, 120, 110, 85, 75, 100, 85, 110, 100, 75, 65, 90, 105, 95, 120, 85]
[-705.0, -142.5, -25.5, -35.0, -809.0, -692.0, -701.5, -129.5, -139.0, -22.0, -722.5, -605.5, -615.0, -43, -52.5, 64.5, -709.5, -719.0, -602.0, -39.5]


In [ ]:
import pandas as pd


df = pd.DataFrame({'text': ['I like kaggle very much',
                            'I do not like kaggle',
                            'I do really love machine learning']})
df

text
0            I like kaggle very much
1               I do not like kaggle
2  I do really love machine learning

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer


vectorizer = CountVectorizer(token_pattern=u'(?u)\\b\\w+\\b')
bag = vectorizer.fit_transform(df['text'])
bag.toarray()

array([[0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1],
       [1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0],
       [1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0]])

In [ ]:
vectorizer.vocabulary_

{'do': 0,
 'i': 1,
 'kaggle': 2,
 'learning': 3,
 'like': 4,
 'love': 5,
 'machine': 6,
 'much': 7,
 'not': 8,
 'really': 9,
 'very': 10}

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

vectorizer = CountVectorizer(token_pattern=u'(?u)\\b\\w+\\b')
transformer = TfidfTransformer()

tf = vectorizer.fit_transform(df['text'])
tfidf = transformer.fit_transform(tf)
# tfidfが計算された結果の表示
print(tfidf.toarray())
# tfidf.toarray()

[[0.         0.31544415 0.40619178 0.         0.40619178 0.
  0.         0.53409337 0.         0.         0.53409337]
 [0.43306685 0.33631504 0.43306685 0.         0.43306685 0.
  0.         0.         0.56943086 0.         0.        ]
 [0.34261996 0.26607496 0.         0.45050407 0.         0.45050407
  0.45050407 0.         0.         0.45050407 0.        ]]


In [ ]:
from gensim.models import word2vec

sentences = [d.split() for d in df['text']]
model = word2vec.Word2Vec(sentences, size=10, min_count=1, window=2, seed=7)
model.wv['like']

array([ 0.02035965, -0.03885538, -0.01550631, -0.02802542, -0.00528814,
       -0.0426371 ,  0.02833652, -0.0412659 , -0.04552319, -0.03982352],
      dtype=float32)

In [ ]:
model.wv.most_similar('like')

[('kaggle', 0.23046481609344482),
 ('do', 0.1817757487297058),
 ('love', 0.14202915132045746),
 ('not', 0.13905853033065796),
 ('machine', 0.1099456176161766),
 ('much', 0.09190084040164948),
 ('I', 0.06309619545936584),
 ('really', 0.05009027570486069),
 ('learning', -0.1309565156698227),
 ('very', -0.21917657554149628)]

In [ ]:
df['text'][0].split()

['I', 'like', 'kaggle', 'very', 'much']

In [ ]:
import numpy as np

wordvec = np.array([model.wv[word] for word in df['text'][0].split()])
wordvec

array([[ 0.01128621,  0.00900978,  0.02682156, -0.02683943,  0.01596994,
         0.03249361, -0.04471587, -0.02947759, -0.02170909, -0.02158526],
       [ 0.02035965, -0.03885538, -0.01550631, -0.02802542, -0.00528814,
        -0.0426371 ,  0.02833652, -0.0412659 , -0.04552319, -0.03982352],
       [ 0.04613282,  0.00831326, -0.0186557 , -0.02674819,  0.00875878,
         0.02311796,  0.03465216,  0.00673563, -0.02741229,  0.01710127],
       [-0.00976335,  0.02489698,  0.009685  , -0.02673005, -0.01704488,
         0.00804923,  0.01082479, -0.03546276,  0.04586815,  0.01440108],
       [ 0.02950664, -0.01529649, -0.00056406,  0.02281829, -0.01803183,
         0.00624455, -0.03073999, -0.03473957, -0.02602273,  0.03497289]],
      dtype=float32)

In [ ]:
np.mean(wordvec, axis=0)

array([ 0.01950439, -0.00238637,  0.0003561 , -0.01710496, -0.00312723,
        0.00545365, -0.00032848, -0.02684204, -0.01495983,  0.00101329],
      dtype=float32)

In [ ]:
np.max(wordvec, axis=0)

array([0.04613282, 0.02489698, 0.02682156, 0.02281829, 0.01596994,
       0.03249361, 0.03465216, 0.00673563, 0.04586815, 0.03497289],
      dtype=float32)

In [ ]:
!pip install pyqubo

In [ ]:
from pyqubo import Binary, solve_qubo

# １日の時間
one_day_time = 5

a = Binary("仕事")           # 8時間 
b = Binary("お風呂")         # 0.5時間
c = Binary("ご飯")           # 1時間
d = Binary("洗濯")           # 0.5時間
e = Binary("掃除")           # 0.5時間
f = Binary("お勤め1(IT系)")   # １時間
g = Binary("お勤め2(ギター)") # 2時間
h = Binary("テレビ")          # 1時間
i = Binary("twitter")         # 1時間
j = Binary("Youtube")         # 1時間
k = Binary("睡眠")            # 8時間
l = Binary("日々の悩み")      # 1時間

H = (one_day_time - a*8 - b*0.5 - c*1 - d*0.5 - e*0.5 - f*1 - g*2 - h*1 - i*1 - j*1 - k*8 -l*1)**2

qubo, offset = H.compile().to_qubo()
solution = solve_qubo(qubo)
print(solution)

{'Youtube': 0, 'twitter': 0, 'お勤め1(IT系)': 0, 'お勤め2(ギター)': 1, 'お風呂': 0, 'ご飯': 1, 'テレビ': 1, '仕事': 0, '掃除': 1, '日々の悩み': 0, '洗濯': 1, '睡眠': 0}


In [ ]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

print(tf.__version__)

2.5.0-dev20210218


In [ ]:
!pip install transformers

     |████████████████████████████████| 2.1MB 12.0MB/s 
     |████████████████████████████████| 901kB 59.9MB/s 
     |████████████████████████████████| 3.3MB 66.0MB/s 


In [ ]:
from transformers import AutoModelForQuestionAnswering, AutoTokenizer, pipeline
model_name = "distilbert-base-uncased-distilled-squad"

# a) Get predictions
nlp = pipeline('question-answering', model=model_name, tokenizer=model_name)

# model = AutoModelForQuestionAnswering.from_pretrained(model_name)
# tokenizer = AutoTokenizer.from_pretrained(model_name)

In [ ]:
QA_input = {
    'question': "チャージ料金はいくらですか？",
    'context': 'チャージ料金 1500円また、アルコール類を500円より提供しております。'
}
res = nlp(QA_input)
print(res)
print('答え: ' + res['answer'])

In [ ]:
QA_input = {
    'question': "アルコール類はいくらですか？",
    'context': 'チャージ料金 1500円また、アルコール類を500円より提供しております。'
}
res = nlp(QA_input)
print(res)
print('答え: ' + res['answer'])

{'score': 0.027067013084888458, 'start': 15, 'end': 28, 'answer': 'アルコール類を500円より'}
答え: アルコール類を500円より
